server:
  port: 8087
  servlet:
    context-path: /bumblebee_user
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        exclude: all
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

jwt:
  sessionTime: 120000000
  secret: secret_key

